/*
 * This source file was generated by the Gradle 'init' task
 */
package javawebserver;

import java.io.IOException;
import static javawebserver.HttpMethod.GET;;

public class App {

    public static void main(String[] args) throws IOException {
        Server myServer = new Server(8080);
        System.out.println("Starting webserver appliction..");
        myServer.addRoute(GET, "/testOne",
                (req) -> new HttpResponse.Builder()
                    .setStatusCode(200)
                    .addHeader("Content-Type", "text/html")
                    .setEntity("<HTML><P>Hello there...</P></HTML>")
                    .build());
        myServer.start();
    }
}
